#!/bin/bash

echo "Building wappspector PHAR..."

cd /opt/cpanel/ea-wappspector

export COMPOSER_ALLOW_SUPERUSER=1

# Install composer
/usr/local/cpanel/3rdparty/bin/php composer-installer.php

# Install dependencies
/usr/local/cpanel/3rdparty/bin/php composer.phar require clue/phar-composer --no-interaction
/usr/local/cpanel/3rdparty/bin/php composer.phar install --no-interaction

# Build wappspector.phar
/usr/local/cpanel/3rdparty/bin/php -d phar.readonly=off vendor/bin/phar-composer build .

unset COMPOSER_ALLOW_SUPERUSER

echo "wappspector installation complete!"